### PR TITLE
NIST-800-53 Revision 5

### PR DESCRIPTION
**Pull request by isimluk**
https://www.nist.gov/blogs/cybersecurity-insights/next-generation-security-and-privacy-controls-protecting-nations

This is generated automatically from https://github.com/usnistgov/oscal-content/blob/71c0209fd00abc5bd6973381f9ebe42d44391ae6/nist.gov/SP800-53/rev5/xml/NIST_SP-800-53_rev5-FINAL_catalog.xml

```
gocomply_oscalkit convert opencontrol -o nist-800-53-rev5.yaml usnistgov/oscal-content/src/nist.gov/SP800-53/rev5/xml/NIST_SP-800-53_rev5-FINAL_catalog.xml
```

### CODE REVIEW

**Comment by shawndwells** [comment]
Noting this is still WIP, a few comments:

* Could you also create nist-800-53-latest?
* What should use for the ``name`` field? Prior versions follow ``name: NIST-800-53 rev4``. Ref:
https://github.com/opencontrol/standards/blob/master/nist-800-53-rev4.yaml#L1
https://github.com/opencontrol/standards/blob/master/nist-800-53-rev3.yaml#L1

**Comment by isimluk** [comment]
> Could you also create nist-800-53-latest?

I would advocate for some grace period before we update `nist-800-53-latest`. Given the mechanics how this standards repo is structured, I would suppose people may only be using the `nist-800-53-latest`. Adding new version (rev5) enables everyone to consume it while adding it as the latest would esentialy force them to consume it.

> What should use for the name field? Prior versions follow name: NIST-800-53 rev4. Ref:

Nice catch. Fixed.

**Comment by shawndwells** [comment]
> > Could you also create nist-800-53-latest?
> 
> I would advocate for some grace period before we update `nist-800-53-latest`. Given the mechanics how this standards repo is structured, I would suppose people may only be using the `nist-800-53-latest`. Adding new version (rev5) enables everyone to consume it while adding it as the latest would esentialy force them to consume it.
> 

Agreed on many people using ``-latest`` and still torn. Usage of ``-latest`` implies willingness for, well, latest content that may change without notice. If consumers only wanted rev4 they could insulate themselves against changes by explicitly calling out a revision.

> > What should use for the name field? Prior versions follow name: NIST-800-53 rev4. Ref:
> 
> Nice catch. Fixed.

**Review by shawndwells — APPROVED** [review]

**Comment by isimluk** [comment]
> > > Could you also create nist-800-53-latest?
> > 
> > 
> > I would advocate for some grace period before we update `nist-800-53-latest`. Given the mechanics how this standards repo is structured, I would suppose people may only be using the `nist-800-53-latest`. Adding new version (rev5) enables everyone to consume it while adding it as the latest would esentialy force them to consume it.
> 
> Agreed on many people using `-latest` and still torn. Usage of `-latest` implies willingness for, well, latest content that may change without notice. If consumers only wanted rev4 they could insulate themselves against changes by explicitly calling out a revision.
> 

Agree to certain extent.

Problem I am focusing on is that `-latest` is internal to this repo. To the outside world (whoever consumes this masonry) we don't export the name `-latest`. Standard names that are in fact exported from this masonry are show on Exhibit A:

Exhibit A

As we can see, there is no `-latest` item in the masonry, instead there is plain NIST-800-53 that happens to be the `-latest`.


As a reminder, there is no easy way for masonry consumers to switch between standard versions. Opencontrol was design in a way that require each Control object to refer to the standard (see [Exhibit B](https://github.com/ComplianceAsCode/redhat/blob/master/openshift-container-platform-4/policies/AC-Access_Control/component.yaml#L13-L14)). Therefore, I am inclined to offer some grace period before updating the `-latest`. Will submit separate PR for that.

**Comment by isimluk** [comment]
Note rev5 differs rather substantially to rev4. Here I tried to make the differences stand out: https://github.com/isimluk/standards/commit/9020a34490d897b66f608495e3eb694d1efa6831

**Comment by shawndwells** [comment]
Thanks for the docs and screenshots! Really helps those who may come behind us and try to build an understanding of the repos, code, and decisions.

Merging this now and we'll revisit the ``-latest`` in a few weeks.

**Pull request merged**
